name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: jackin-project/validate-agent-action@84ed8ed39fb0fdb463786ec54c1099a89a39ebda # latest
        with:
          jackin-version: latest-build
